### PR TITLE
Updates to reflect that it's not just for SDP

### PR DESCRIPTION
**Pull request by bmerry**
The controller is no longer SDP-specific, being used for the new CBF as well. Update it to remove the "SDP" term from a number of classes, docstrings, web page titles etc. This should have no functional impact, and is just designed to reduce programmer and user confusion.

I'm not totally happy with changing `tasks.SDPLogicalTask` to `tasks.LogicalTask` because it now has the same base name as `scheduler.LogicalTask` (the same applies to PhysicalTask etc). If anyone has a better name to reflect that this is the version with extra sauce that is specific to the use case within the product controller rather than suitable for a general-purpose scheduler I'm open to suggestions.

Closes NGC-546.

### CODE REVIEW

**Comment by ludwigschwardt** [comment]
`tasks.PCLogicalTask`? :-)

**Comment by bmerry** [comment]
> `tasks.PCLogicalTask`? slightly_smiling_face Goes well with "PC Load Letter".

You joke, but it's not the worst idea. Or maybe `tasks.ProductLogicalTask`, since the task is not part of the controller but the product. It is a bit of a mouthful though.

**Comment by ludwigschwardt** [comment]
I put some thought into that, and only saw the joke later... 😁 I like your suggestion too.

**Comment by richarms** [comment]
I agree that it would be better to have a name for `task.LogicalTask` that is distinct from `scheduler.LogicalTask`. It may mean more renaming, but one option would be to rename the parent class to `scheduler.abstractLogicalTask`, which would still be distinct from the abstract base class `scheduler.LogicalNode` in the hierarchy. However, that said, I'm fine with it as it is.

**Review by richarms — APPROVED** [review]

**Comment by bmerry** [comment]
> I agree that it would be better to have a name for `task.LogicalTask` that is distinct from `scheduler.LogicalTask`. It may mean more renaming, but one option would be to rename the parent class to `scheduler.abstractLogicalTask`, which would still be distinct from the abstract base class `scheduler.LogicalNode` in the hierarchy. However, that said, I'm fine with it as it is.

I wasn't so keen on scheduler.AbstractLogicalTask, because it's not an abstract class i.e. it can be instantiated and used as is. I went with tasks.ProductLogicalTask etc. It's longer but there were only 3 places where I had to wrap lines to keep flake8 happy with line lengths.

**Comment by ludwigschwardt** [comment]
Sorry for the late remark... There is/was also the option of leaving it as
```python
import tasks
isinstance(task, tasks.LogicalTask)
```
Although I guess `tasks` is not very descriptive either (but shorter).

**Review by james-smith-za — APPROVED** [review]
LGTM.

**Review by richarms — APPROVED** [review]

**Pull request merged**
